
export const dictionary = [
  { id: "0", className: "st0", isSelected: "false", cityname: "Danniye", governorates: "North Lebanon", places :["hamra", "borj", "1"]},
  { id: "1", className: "st1", isSelected: "false", cityname: "Baalbek", governorates: "Baalbek", places :["hamra", "borj", "2"]},
  { id: "2", className: "st2", isSelected: "false", cityname: "Batroun", governorates: "North Lebanon", places :["hamra", "borj", "3"]},
  { id: "3", className: "st3", isSelected: "false", cityname: "Koura", governorates: "North Lebanon", places :["hamra", "borj", "4"]},
  { id: "4", className: "st4", isSelected: "false", cityname: "Tripoli", governorates: "North Lebanon", places :["hamra", "borj", "5"]},
  { id: "5", className: "st5", isSelected: "false", cityname: "Bshari", governorates: "North Lebanon", places :["hamra", "borj", "6"]},
  { id: "6", className: "st6", isSelected: "false", cityname: "Zgharta", governorates: "North Lebanon", places :["hamra", "borj", "7"]},
  { id: "7", className: "st7", isSelected: "false", cityname: "Hasbaya", governorates: "Nabatieh", places :["hamra", "borj"]},
  { id: "8", className: "st8", isSelected: "false", cityname: "Nabatieh", governorates: "Nabatieh", places :["hamra", "borj"]},
  { id: "9", className: "st9", isSelected: "false", cityname: "Bint Jbeil", governorates: "Nabatieh", places :["hamra", "borj"]},
  { id: "10", className: "st10", isSelected: "false", cityname: "Marjeyoun", governorates: "Nabatieh", places :["hamra", "borj"]},
  { id: "11", className: "st11", isSelected: "false", cityname: "Sour", governorates: "South Lebanon", places :["hamra", "borj"]},
  { id: "12", className: "st12", isSelected: "false", cityname: "Hermel", governorates: "Baalbek", places :["hamra", "borj"]},
  { id: "13", className: "st13", isSelected: "false", cityname: "Akkar", governorates: "Akkar", places :["hamra", "borj"]},
  { id: "14", className: "st14", isSelected: "false", cityname: "Jbeil", governorates: "Keserwan-Jbeil", places :["hamra", "borj"]},
  { id: "15", className: "st15", isSelected: "false", cityname: "Kesrwan", governorates: "Keserwan-Jbeil", places :["hamra", "borj"]},
  { id: "16", className: "st16", isSelected: "false", cityname: "Baabda", governorates: "Mount Lebanon", places :["hamra", "borj"]},
  { id: "17", className: "st17", isSelected: "false", cityname: "Aley", governorates: "Mount Lebanon", places :["hamra", "borj"]},
  { id: "18", className: "st18", isSelected: "false", cityname: "Matn", governorates: "Mount Lebanon", places :["hamra", "borj"]},
  { id: "19", className: "st19", isSelected: "false", cityname: "Chouf", governorates: "Mount Lebanon", places :["hamra", "borj"]},
  { id: "20", className: "st20", isSelected: "false", cityname: "Zahle", governorates: "Beqaa", places :["hamra", "borj"]},
  { id: "21", className: "st21", isSelected: "false", cityname: "Rashaya", governorates: "Beqaa", places :["hamra", "borj"]},
  { id: "22", className: "st22", isSelected: "false", cityname: "Beqaa algharbi", governorates: "Beqaa", places :["hamra", "borj"]},
  { id: "23", className: "st23", isSelected: "false", cityname: "Jezzin", governorates: "South Lebanon", places :["hamra", "borj"]},
  { id: "24", className: "st24", isSelected: "false", cityname: "Sidon", governorates: "South Lebanon", places :["hamra", "borj"]},
  { id: "25", className: "st25", isSelected: "false", cityname: "Beirut", governorates: "Beirut", places :["hamra", "borj"]}
]


export const placesdictionary = [
  { id: "0", selectedplaces :[] },
  { id: "1", selectedplaces :[] },
  { id: "2", selectedplaces :[] },
  { id: "3", selectedplaces :[] },
  { id: "4", selectedplaces :[]  },
  { id: "5", selectedplaces :[] },
  { id: "6", selectedplaces :[] },
  { id: "7", selectedplaces :[] },
  { id: "8", selectedplaces :[] },
  { id: "9", selectedplaces :[] },
  { id: "10", selectedplaces :[] },
  { id: "11", selectedplaces :[] },
  { id: "12", selectedplaces :[] },
  { id: "13", selectedplaces :[] },
  { id: "14", selectedplaces :[] },
  { id: "15", selectedplaces :[] },
  { id: "16",  selectedplaces :[] },
  { id: "17", selectedplaces :[] },
  { id: "18", selectedplaces :[] },
  { id: "19", selectedplaces :[] },
  { id: "20", selectedplaces :[] },
  { id: "21", selectedplaces :[] },
  { id: "22", selectedplaces :[]},
  { id: "23", selectedplaces :[] },
  { id: "24", selectedplaces :[] },
  { id: "25", selectedplaces :[] }
]

